In [1]:
import torch

In [2]:
if torch.cuda.is_available():
  print("gpu available")
  print(f"Using gpu:{torch.cuda.get_device_name(0)}")
else:
  print("gpu not available")

gpu available
Using gpu:Tesla T4


In [3]:
#creating tensor

In [4]:
a=torch.empty(2,3)
print(a)

tensor([[4.7851e+22, 2.8826e+32, 4.4248e+30],
        [7.2442e+22, 2.3086e-12, 7.2646e+22]])


In [5]:
type(a)

torch.Tensor

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.8626, 0.1453, 0.2474],
        [0.3119, 0.6666, 0.3744]])

In [8]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
#arrange
print(torch.arange(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [12]:
#using linspace
print(torch.linspace(0,10,10))

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [13]:
#using eye
print(torch.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [14]:
#using full
print(torch.full((2,3),6))

tensor([[6, 6, 6],
        [6, 6, 6]])


In [15]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068092717625322805, 4122265046979588401],
        [6501006750839615534, 7309453675965983778, 8315168162784306286]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

TENSOR DATATYPES

In [21]:
x.dtype

torch.int64

In [22]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical operations

In [25]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [26]:
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [27]:
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [28]:
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [29]:
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [30]:
#int division
(x*100)//3

tensor([[23., 26.],
        [13., 30.]])

In [31]:
#mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [32]:
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [33]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [34]:
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [35]:
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [36]:
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [37]:
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [38]:
#abs
c=torch.tensor([1,-2,3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [39]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [40]:
d=torch.tensor([1.9,2.3,3.7,4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [41]:
torch.ceil(d)


tensor([2., 3., 4., 5.])

In [42]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [43]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

Reduction operation


In [44]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e


tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [45]:
#sum
torch.sum(e)

tensor(24.)

In [46]:
torch.sum(e,dim=0) #sum along columns

tensor([ 8.,  0., 16.])

In [47]:
#sum along rows
torch.sum(e,dim=1)

tensor([15.,  9.])

In [48]:
#mean
torch.mean(e)

tensor(4.)

In [49]:
torch.mean(e,dim=0)

tensor([4., 0., 8.])

In [51]:
torch.mean(e,dim=1)

tensor([5., 3.])

In [54]:
torch.median(e)

tensor(0.)

In [55]:
torch.max(e)

tensor(9.)

In [56]:
torch.min(e)

tensor(0.)

In [57]:
torch.prod(e)

tensor(0.)

In [58]:
torch.std(e)

tensor(4.4272)

In [59]:
torch.var(e)

tensor(19.6000)

In [60]:
torch.argmax(e)

tensor(5)

In [61]:
torch.argmin(e)

tensor(1)

Matrix Operations

In [62]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [63]:
#matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [65]:
#dot product
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
torch.dot(vector1,vector2)

tensor(11)

In [68]:
#transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [71]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [72]:
torch.det(h)

tensor(-110.)

In [73]:
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

Comparison Operations

In [74]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [79]:
print(i>j)
print(i<j)
print(i==j)
print(i!=j)


tensor([[ True,  True, False],
        [ True, False, False]])
tensor([[False, False,  True],
        [False,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


Special Functions

In [80]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [81]:
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [82]:
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [83]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [84]:
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [85]:
torch.softmax(k,dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [86]:
#relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

Inplace Operations

In [87]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)


tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [92]:
m.add_(n) #using _ means after addition the value will updated to m

tensor([[2.1335, 0.5695, 2.9268],
        [1.9610, 0.5856, 3.5416]])

In [91]:
m

tensor([[1.6414, 0.4947, 1.9663],
        [1.6339, 0.5753, 2.5900]])

In [93]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [94]:
torch.relu_(m)

tensor([[2.1335, 0.5695, 2.9268],
        [1.9610, 0.5856, 3.5416]])

In [95]:
m

tensor([[2.1335, 0.5695, 2.9268],
        [1.9610, 0.5856, 3.5416]])

Copying a tensor

In [96]:
a=torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [97]:
b=a

In [98]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [99]:
a[0][0]=0

In [100]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [101]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [102]:
id(a)

137306532802752

In [103]:
id(b)

137306532802752

In [104]:
b=a.clone()

In [105]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [106]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [107]:
a[0][0]=10

In [108]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [109]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [110]:
id(a)

137306532802752

In [111]:
id(b)

137306533040192